### ISSUE TITLE
Name Component & Fragment Pattern 

### ISSUE THREAD

**Issue by ElhamFadel** [GSG-G11/fresh-pet#34]
https://github.com/GSG-G11/fresh-pet/blob/9a35febc492fd259d1d1deec2b57fc569e6e8601/client/src/components/Modal/index.jsx#L10

[See this note ](https://github.com/GSG-G11/tasty/issues/18#issue-1186449248)

and there's very important note 
```Name Components``` 
It helps when you’re reading an error stack trace and using the React Dev Tools.
So avoid name it ```index```.

See you later,
Elham

**Comment by AhmedQeshta** [comment]
Thank You For these notes, I will do it later.
💎
